import { defineField } from 'sanity';

/** Fields shared by course and cpd. Never write Level 3, Ofqual, NVQ or "regulated" in Mat, Reformer or Barre copy. */
export const courseFields = [
  defineField({ name: 'title', title: 'Title (H1, includes the keyword)', type: 'string', validation: (r) => r.required() }),
  defineField({ name: 'shortTitle', title: 'Short title (cards and nav)', type: 'string', validation: (r) => r.required() }),
  defineField({ name: 'slug', type: 'slug', options: { source: 'shortTitle' }, validation: (r) => r.required() }),
  defineField({ name: 'order', title: 'Sort order', type: 'number' }),
  defineField({ name: 'path', type: 'string', options: { list: ['qualify', 'continue'] }, validation: (r) => r.required() }),
  defineField({ name: 'kind', type: 'string', options: { list: ['teacher-training', 'apparatus', 'cpd', 'bundle'] }, validation: (r) => r.required() }),
  defineField({ name: 'discipline', type: 'string', description: 'Mat, Reformer, Barre, Chair, Cadillac, Barrels…' }),
  defineField({ name: 'level', type: 'string', description: 'e.g. Beginner, Intermediate and Advanced. Never "Level 3".' }),
  defineField({ name: 'format', type: 'string', options: { list: ['in-person', 'online'] }, initialValue: 'in-person' }),
  defineField({ name: 'eyebrow', type: 'string', description: 'e.g. Teacher training · 5 in-person days' }),
  defineField({ name: 'outcome', title: 'One-line outcome', type: 'text', rows: 2 }),
  defineField({ name: 'bestFor', title: '"Best for" line (hubs)', type: 'text', rows: 2 }),
  defineField({ name: 'price', title: 'Price (£)', type: 'number', description: 'Leave empty to show "Price on request".' }),
  defineField({ name: 'financeOptions', type: 'array', of: [{ type: 'financeOption' }] }),
  defineField({ name: 'prerequisites', type: 'array', of: [{ type: 'string' }], description: 'Only place where a prior qualification may be named.' }),
  defineField({ name: 'inclusions', type: 'array', of: [{ type: 'string' }] }),
  defineField({ name: 'curriculum', type: 'array', of: [{ type: 'curriculumGroup' }] }),
  defineField({ name: 'durationDays', title: 'Course length (days)', type: 'number', description: 'Shown on the course page, pricing table and in search results. Leave empty if not yet confirmed.', validation: (r) => r.min(1).integer() }),
  defineField({ name: 'hoursBreakdown', type: 'hoursBreakdown' }),
  defineField({ name: 'exams', type: 'array', of: [{ type: 'exam' }] }),
  defineField({ name: 'forYou', title: 'This is for you if', type: 'array', of: [{ type: 'string' }], description: 'Positive framing only. The site never shows a "This isn\'t for you" list.' }),
  defineField({ name: 'afterBooking', title: 'What happens after you book', type: 'array', of: [{ type: 'string' }] }),
  defineField({ name: 'unlocks', title: 'Unlocks (course slugs)', type: 'array', of: [{ type: 'string' }] }),
  defineField({ name: 'accreditation', title: 'Accreditation (this course)', type: 'string', description: 'Exact wording for this course, e.g. "Internationally accredited by ITTAP via the Pilates Method Alliance". Leave empty to hide. CIMSPA does not endorse the Mat course.' }),
  defineField({ name: 'accreditationBadges', title: 'Accreditation badges (this course)', type: 'array', of: [{ type: 'string' }], description: 'Names from Site settings > Accreditation badges to show on this course, e.g. ITTAP, Pilates Method Alliance, Barre Fitness Alliance.' }),
  defineField({ name: 'locationNote', title: 'Location note', type: 'string', description: 'e.g. "Most dates at our Altrincham training centre; around half a dozen a year run elsewhere in the UK and abroad".' }),
  defineField({ name: 'timeToCertify', title: 'Time to certify', type: 'string', description: 'e.g. "Usually around 6 months, anywhere from 3 to 12". Never "8 weeks".' }),
  defineField({ name: 'heroImage', type: 'imageWithAlt', description: 'Also the poster frame when a hero video is set.' }),
  defineField({ name: 'cardImage', title: 'Card image (16:9 graphic)', type: 'imageWithAlt', description: 'Shown on course cards. Falls back to the hero image.' }),
  defineField({ name: 'heroVideo', title: 'Hero video (path)', type: 'string', description: 'Optional, e.g. /video/advanced-reformer. Files are added to the site by the developer from a 1920×1080 MP4.', validation: (r) => r.regex(/^\/video\/[a-z0-9-]+$/, { name: 'video path' }) }),
  defineField({ name: 'gallery', type: 'array', of: [{ type: 'imageWithAlt' }] }),
  defineField({ name: 'faqs', type: 'array', of: [{ type: 'reference', to: [{ type: 'faq' }] }] }),
  defineField({ name: 'testimonials', type: 'array', of: [{ type: 'reference', to: [{ type: 'testimonial' }] }] }),
  defineField({ name: 'answerQuestion', title: 'Answer box question (H2)', type: 'string' }),
  defineField({ name: 'answerSummary', title: 'Answer summary (40 to 60 words)', type: 'text', rows: 4, validation: (r) => r.required().custom((v?: string) => { const n = (v ?? '').trim().split(/\s+/).length; return n >= 35 && n <= 70 ? true : 'Aim for 40 to 60 words'; }) }),
  defineField({ name: 'arketaFallbackUrl', title: 'Arketa link (when no date is selected)', type: 'string', description: 'Path after https://app.arketa.co/iframe/pilatesprogramme/' }),
  defineField({ name: 'guideUrl', title: 'Course guide PDF URL', type: 'url' }),
  defineField({ name: 'seo', type: 'seo' }),
];
