import { defineField } from 'sanity';

/** Fields shared by course and cpd. Never write Level 3, Ofqual, NVQ or "regulated" in Mat, Reformer or Barre copy. */
export const courseFields = [
  defineField({ name: 'title', title: 'Title (H1, includes the keyword)', type: 'string', validation: (r) => r.required() }),
  defineField({ name: 'shortTitle', title: 'Short title (cards and nav)', type: 'string', validation: (r) => r.required() }),
  defineField({ name: 'slug', type: 'slug', options: { source: 'shortTitle' }, validation: (r) => r.required() }),
  defineField({ name: 'order', title: 'Sort order', type: 'number' }),
  defineField({ name: 'path', type: 'string', options: { list: ['qualify', 'continue'] }, validation: (r) => r.required() }),
  defineField({ name: 'kind', type: 'string', options: { list: ['teacher-training', 'apparatus', 'cpd', 'bundle'] }, validation: (r) => r.required() }),
  defineField({ name: 'discipline', type: 'string', description: 'Mat, Reformer, Barre, Chair, Cadillac, Barrels…' }),
  defineField({ name: 'level', type: 'string', description: 'e.g. Beginner, Intermediate and Advanced. Never "Level 3".' }),
  defineField({ name: 'format', type: 'string', options: { list: ['in-person', 'online'] }, initialValue: 'in-person' }),
  defineField({ name: 'eyebrow', type: 'string', description: 'e.g. Teacher training · 5 in-person days' }),
  defineField({ name: 'outcome', title: 'One-line outcome', type: 'text', rows: 2 }),
  defineField({ name: 'bestFor', title: '"Best for" line (hubs)', type: 'text', rows: 2 }),
  defineField({ name: 'price', title: 'Price (£)', type: 'number', description: 'Leave empty to show "Price on request".' }),
  defineField({ name: 'financeOptions', type: 'array', of: [{ type: 'financeOption' }] }),
  defineField({ name: 'prerequisites', type: 'array', of: [{ type: 'string' }], description: 'Only place where a prior qualification may be named.' }),
  defineField({ name: 'inclusions', type: 'array', of: [{ type: 'string' }] }),
  defineField({ name: 'curriculum', type: 'array', of: [{ type: 'curriculumGroup' }] }),
  defineField({ name: 'hoursBreakdown', type: 'hoursBreakdown' }),
  defineField({ name: 'exams', type: 'array', of: [{ type: 'exam' }] }),
  defineField({ name: 'forYou', title: 'This is for you if', type: 'array', of: [{ type: 'string' }] }),
  defineField({ name: 'notForYou', title: "This isn't for you if", type: 'array', of: [{ type: 'string' }] }),
  defineField({ name: 'afterBooking', title: 'What happens after you book', type: 'array', of: [{ type: 'string' }] }),
  defineField({ name: 'unlocks', title: 'Unlocks (course slugs)', type: 'array', of: [{ type: 'string' }] }),
  defineField({ name: 'heroImage', type: 'imageWithAlt' }),
  defineField({ name: 'gallery', type: 'array', of: [{ type: 'imageWithAlt' }] }),
  defineField({ name: 'faqs', type: 'array', of: [{ type: 'reference', to: [{ type: 'faq' }] }] }),
  defineField({ name: 'testimonials', type: 'array', of: [{ type: 'reference', to: [{ type: 'testimonial' }] }] }),
  defineField({ name: 'answerQuestion', title: 'Answer box question (H2)', type: 'string' }),
  defineField({ name: 'answerSummary', title: 'Answer summary (40 to 60 words)', type: 'text', rows: 4, validation: (r) => r.required().custom((v?: string) => { const n = (v ?? '').trim().split(/\s+/).length; return n >= 35 && n <= 70 ? true : 'Aim for 40 to 60 words'; }) }),
  defineField({ name: 'arketaFallbackUrl', title: 'Arketa link (when no date is selected)', type: 'string', description: 'Path after https://app.arketa.co/iframe/pilatesprogramme/' }),
  defineField({ name: 'guideUrl', title: 'Course guide PDF URL', type: 'url' }),
  defineField({ name: 'seo', type: 'seo' }),
];
