import { defineField, defineType } from 'sanity';
export default defineType({
  name: 'job', title: 'Job', type: 'document',
  description: 'Approve only genuine roles at real studios. Use the Approve / Reject actions so emails and dates are set correctly.',
  fields: [
    defineField({ name: 'status', type: 'string', options: { list: ['pending', 'approved', 'rejected', 'expired'] }, initialValue: 'pending' }),
    defineField({ name: 'title', type: 'string', validation: (r) => r.required() }),
    defineField({ name: 'slug', type: 'slug', options: { source: 'title' }, validation: (r) => r.required() }),
    defineField({ name: 'studio', title: 'Studio (reference)', type: 'reference', to: [{ type: 'studio' }] }),
    defineField({ name: 'studioInline', title: 'Studio (as submitted)', type: 'object', fields: [defineField({ name: 'name', type: 'string' }), defineField({ name: 'website', type: 'url' }), defineField({ name: 'town', type: 'string' }), defineField({ name: 'postcode', type: 'string' })] }),
    defineField({ name: 'contactName', type: 'string' }),
    defineField({ name: 'submitterEmail', type: 'string' }),
    defineField({ name: 'location', type: 'string' }),
    defineField({ name: 'town', type: 'string' }),
    defineField({ name: 'postcode', type: 'string' }),
    defineField({ name: 'employmentType', type: 'string', options: { list: ['FULL_TIME', 'PART_TIME', 'CONTRACTOR', 'TEMPORARY', 'INTERN', 'VOLUNTEER', 'PER_DIEM', 'OTHER'] } }),
    defineField({ name: 'payMin', type: 'number' }),
    defineField({ name: 'payMax', type: 'number' }),
    defineField({ name: 'payUnit', type: 'string', options: { list: ['HOUR', 'CLASS', 'DAY', 'WEEK', 'MONTH', 'YEAR'] } }),
    defineField({ name: 'disciplines', type: 'array', of: [{ type: 'string' }] }),
    defineField({ name: 'requirements', type: 'text', rows: 4 }),
    defineField({ name: 'description', type: 'text', rows: 10, validation: (r) => r.max(2000) }),
    defineField({ name: 'applyUrl', type: 'url' }),
    defineField({ name: 'applyEmail', type: 'string' }),
    defineField({ name: 'datePosted', type: 'date', description: 'Set automatically on approval.' }),
    defineField({ name: 'validThrough', type: 'date', description: 'Defaults to 60 days from submission. Expiry cron hides the role after this date.' }),
    defineField({ name: 'featuredGraduateFriendly', title: 'Graduate friendly', type: 'boolean', initialValue: false }),
    defineField({ name: 'rejectReason', type: 'text', rows: 2 }),
    defineField({ name: 'submittedAt', type: 'datetime', readOnly: true }),
    defineField({ name: 'approvedAt', type: 'datetime', readOnly: true }),
    defineField({ name: 'reminderSentFor', type: 'date', readOnly: true, hidden: true }),
  ],
  preview: { select: { title: 'title', subtitle: 'studioInline.name', status: 'status' }, prepare: ({ title, subtitle, status }) => ({ title, subtitle: `${status ?? ''} · ${subtitle ?? ''}` }) },
});
