import { defineField, defineType } from 'sanity';
export default defineType({
  name: 'siteSettings', title: 'Site settings', type: 'document',
  fields: [
    defineField({ name: 'siteName', type: 'string' }),
    defineField({ name: 'entityName', type: 'string', description: 'Always "The Pilates Programme, Altrincham"' }),
    defineField({ name: 'tagline', type: 'text', rows: 2 }),
    defineField({ name: 'email', type: 'string' }),
    defineField({ name: 'instagram', type: 'string' }),
    defineField({ name: 'instagramUrl', type: 'url' }),
    defineField({ name: 'address', type: 'object', fields: [defineField({ name: 'street', type: 'string' }), defineField({ name: 'town', type: 'string' }), defineField({ name: 'postcode', type: 'string' }), defineField({ name: 'country', type: 'string' })] }),
    defineField({ name: 'geo', type: 'object', fields: [defineField({ name: 'lat', type: 'number' }), defineField({ name: 'lng', type: 'number' })] }),
    defineField({ name: 'mapUrl', type: 'url' }),
    defineField({ name: 'logo', title: 'Logo (SVG preferred)', type: 'imageWithAlt' }),
    defineField({ name: 'accreditationBadges', type: 'array', of: [{ type: 'object', fields: [defineField({ name: 'name', type: 'string' }), defineField({ name: 'image', type: 'imageWithAlt' }), defineField({ name: 'url', type: 'url' })] }] }),
    defineField({ name: 'accreditationStatements', title: 'Approved accreditation wording (one per body)', type: 'array', of: [{ type: 'string' }] }),
    defineField({ name: 'accreditationCareer', title: 'What accreditation means for your career', type: 'text', rows: 4 }),
    defineField({ name: 'accreditationEmployerNote', title: 'Employer requirements note (optional)', type: 'text', rows: 3, description: 'If this mentions regulated qualifications, add the exact sentence to scripts/banned-terms.allowlist.json before publishing.' }),
    defineField({ name: 'proofStats', title: 'Proof bar stats (hidden when empty)', type: 'array', of: [{ type: 'object', fields: [defineField({ name: 'label', type: 'string' }), defineField({ name: 'value', type: 'string' })] }] }),
    defineField({ name: 'googleReviewUrl', type: 'url' }),
    defineField({ name: 'googleBusinessUrl', type: 'url' }),
    defineField({ name: 'studioHireRate', title: 'Studio hire (£/hour)', type: 'number' }),
    defineField({ name: 'equipmentHireRate', title: 'Equipment hire (£/hour)', type: 'number' }),
    defineField({ name: 'appMonthlyPrice', title: 'App (£/month)', type: 'number' }),
    defineField({ name: 'appStoreUrl', type: 'url' }),
    defineField({ name: 'typicalClassRate', title: 'Typical pay per class (£) for payback maths', type: 'number' }),
    defineField({ name: 'insuranceNote', type: 'text', rows: 2 }),
    defineField({ name: 'travelTimes', type: 'array', of: [{ type: 'object', fields: [defineField({ name: 'from', type: 'string' }), defineField({ name: 'minutes', type: 'number' }), defineField({ name: 'mode', type: 'string' })] }] }),
    defineField({ name: 'parkingNote', type: 'text', rows: 2 }),
    defineField({ name: 'accessibilityNote', type: 'text', rows: 3 }),
    defineField({ name: 'partnerStudios', type: 'array', of: [{ type: 'string' }] }),
    defineField({ name: 'elevatingOthers', type: 'object', fields: [defineField({ name: 'open', title: 'Applications open', type: 'boolean' }), defineField({ name: 'windowNote', type: 'string' }), defineField({ name: 'placesPerYear', type: 'number' }), defineField({ name: 'story', title: "Samhar's story", type: 'text', rows: 6 }), defineField({ name: 'eligibility', type: 'array', of: [{ type: 'string' }] })] }),
    defineField({ name: 'freeGuide', type: 'object', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'bullets', type: 'array', of: [{ type: 'string' }] }), defineField({ name: 'coverImage', type: 'imageWithAlt' }), defineField({ name: 'file', title: 'Guide PDF', type: 'file' })] }),
    defineField({ name: 'continueInclusions', title: 'Continuing education: what is included', type: 'array', of: [{ type: 'string' }], description: 'Shown as a checklist on the Continuing Education hub.' }),
    defineField({ name: 'heroTrustLine', title: 'Hero trust line', type: 'string', description: 'Shown under the hero buttons, e.g. Trusted by 850+ students. Leave empty to hide.' }),
    defineField({ name: 'pressLogos', title: '"As seen in" logos', type: 'array', of: [{ type: 'object', fields: [defineField({ name: 'name', type: 'string' }), defineField({ name: 'image', title: 'Logo (PNG or SVG, dark on transparent)', type: 'imageWithAlt' }), defineField({ name: 'url', type: 'url' })] }], description: 'Shown in greyscale at the bottom of the home hero. Without an image the name renders as a text wordmark.' }),
    defineField({ name: 'cohortCap', title: 'Maximum cohort size', type: 'number' }),
    defineField({ name: 'weekendCohorts', type: 'boolean' }),
  ],
});
